######################################################################
## Config file for Lee and O'Rourke et al. ISS Staph anvio workflow ##
######################################################################

######################################### NOTE #############################################
# Due to difficulties in setting up anvio conda environment, the workflow is meant to be run
# in an active anvio environment, rather than being handled by snakemake. It was setup
# as described here: https://osf.io/8sy2a/wiki/3.%20Pangenomics/
############################################################################################

# file holding unique genome IDs
genome_IDs_file:
    "test-genomes.txt"

# threads for bowtie2 and samtools processes (may be multiplied by number of concurrent jobs running)
mapping_threads:
    20

# threads used in parallelizable distint anvio steps (may be multiplied by the number of concurrent jobs running)
general_anvio_threads:
    20

# threads used in anvio pan (won't be multiplied by number of jobs allowed)
anvio_pan_threads:
    50

# anvio pan mcl inflation
mcl_inflation:
    6

# anvio genomes db name
genomes_db:
    "our-isolates-GENOMES.db"

# anvio pan name argument base (will have mcl and min occurence appended)
anvio_pan_name:
    "ISS_Staph"

# anvio pan output dir
anvio_pan_output_dir:
    "ISS-Staph-pan"

## the following 4 directories should exist already
# path to reads directory
reads_dir:
    "../all-err-corr-reads/"

# path to genbank files dir
genbank_files_dir:
    "all-genbank-files/"

# anvio COGs data dir
anvio_COGs_dir:
    "~/ref-dbs/anvio/COGs/"

# anvio KOs data dir
anvio_KOs_dir:
    "~/ref-dbs/anvio/KOs/"


## the following directories will be created and populated by the workflow
logs_dir:
    "logs/"

input_anvio_files_dir:
    "input-files-for-anvio/"

bam_files_dir:
    "bam-files/"

bowtie2_indexes_dir:
    "bowtie2-indexes/"

contigs_dbs_dir:
    "contigs-dbs/"

profile_dbs_dir:
    "profile-dbs/"
